version: '3.8'
services:

  db:
    container_name: postgres
    image: postgres
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  api:
    container_name: api
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
    - .:/usr/src/app
    env_file:
      - .env
    # healthcheck:
    #   test: ["CMD", "ping" ,"db"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 20s

volumes: 
 data: {}