version: '3.8'
services:
  api:
    container_name: api
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
    - .:/usr/src/app
    env_file:
      - .env

  db:
    container_name: postgres
    image: postgres
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes: 
 data: {}