name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:

  Build:
    runs-on: ubuntu-latest
      
    steps:
      
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: CreateEnv
      run: |
        cd ${{ github.workspace }}
        touch watch-wagon-backend/.env
        echo APP_SECRET=37ryurfhjiuewr9u832tryfh8943 >> watch-wagon-backend/.env
        echo JWT_SECRET=84289rhdjiu2whjd2iue3tr58734hnfiuw3 >> watch-wagon-backend/.env
        echo PORT=5000 >> watch-wagon-backend/.env
        echo DB_USER=postgres >> watch-wagon-backend/.env
        echo DB_HOST='db'  >> watch-wagon-backend/.env
        echo DB_NAME='watchwagon'  >> watch-wagon-backend/.env
        echo DB_PASSWORD='root'  >> watch-wagon-backend/.env
        echo DB_PORT=5432  >> watch-wagon-backend/.env
        touch watch-wagon-main/.env
        echo REACT_APP_MOVIE_API_URL=https://streaming-availability.p.rapidapi.com/ >> watch-wagon-main/.env
        echo REACT_APP_API_URL=http://localhost:8000 >> watch-wagon-main/.env
        echo PORT=3000 >> watch-wagon-main/.env
        
    - name: StartEnv
      run: |
        pwd 
        cd ${{ github.workspace }}
        bash scripts/start.sh

    - name: SetupNode.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Dependencies
      run: |
        cd watch-wagon-backend
        npm install

  Sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'   
    steps:
      - uses: actions/checkout@v2 
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.EC2_HOST}}
            USER_NAME: ${{secrets.USER_NAME}}
      
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

              # Now we have got the access of EC2 and we will start the deploy .
              cd /home/ubuntu/watch-wagon &&
              git checkout main &&
              git fetch --all &&
              git reset --hard origin/main &&
              git pull origin main &&
              bash scripts/start.sh
              '