name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:

    - name: Install SSH Client
      run: sudo apt-get install openssh-client

    - name: Clone Repository on EC2
      run: |
        ssh -i <(echo "${{ secrets.EC2_SSH_KEY }}") ec2-user@ec2-18-231-28-89.sa-east-1.compute.amazonaws.com "echo hello-world >> teste.txt"
